summarizer:  # Configuration for summarizer.
  cls: OpenAISingleDocSummarizer  # name of class that is subclass of OpenAIWithPromptBuilder
  config: # configuration for defined class
    api:  # OpenAI API configuration.
      api_key:  # OpenAI API key.
      base_url: # Base URL for OpenAI API.
    model: gpt-4o-mini # Name of model that should be used.
    prompt_builder: # Prompt builder. Available fields are: doc.
      template:  |  # Jinja2 template for prompt sequence. It can be a string, dictionary with keys 'segment_name' and 'template', or a sequence of messages with role and content. If you use dictionary all parts will be concatenated and SegmentedString will be used for the rendered result.
            Vytvoř krátký souhrn následujícího textu. Souhrn by měl být výstižný a obsahovat klíčové informace z textu. Neměl by být delší než 3 věty.
            Použij současnou češtinu, přestože výsledky vyhledávání ji používat nemusí.
        
            {{doc}}
      role_key_form: role # How the dict key would be named in built prompt sequence. Doesn't effect key name in template config.
      content_key_form: content # How the dict key would be named in built prompt sequence. Doesn't effect key name in template config.
