summarizer:  # Configuration for summarizer.
  cls: OpenAIQueryBasedMultiDocSummarizer  # name of class that is subclass of OpenAIWithPromptBuilder
  config: # configuration for defined class
    api:  # OpenAI API configuration.
      api_key:  # OpenAI API key.
      base_url: # Base URL for OpenAI API.
    model: gpt-4o-mini # Name of model that should be used.
    prompt_builder: # Prompt builder. Available fields are: query, docs.
      template:  |  # Jinja2 template for prompt sequence. It can be a string, dictionary with keys 'segment_name' and 'template', or a sequence of messages with role and content. If you use dictionary all parts will be concatenated and SegmentedString will be used for the rendered result.
            Identifikuj relevantní témata k dotazu uživatele v následujících získaných výsledcích, poté vytvoř stručný popis identifikovaných témat na základě výsledků vyhledávání a vyhledávacího dotazu. Každý z popisů nemá být delší než 100 slov. Snaž se použít všechny výsledky vyhledávání. Při tvorbě souhrnu se nesoustřeď na detaily, ale pouze na hlavní myšlenky popisující dané téma.
            Použij současnou češtinu, přestože výsledky vyhledávání ji používat nemusí.
        
            Uživatel zadal do vyhledávače historických dokumentů dotaz:
        
            {{query}}
        
            Tento dotaz mu vrátil následující výsledky:
        
            {% for d in docs %}Výsledek [{{loop.index}}]: {{d}}
            {% endfor %}

      role_key_form: role # How the dict key would be named in built prompt sequence. Doesn't effect key name in template config.
      content_key_form: content # How the dict key would be named in built prompt sequence. Doesn't effect key name in template config.
    response_format: # Format of the response.
      type: json_schema
      json_schema:
        name: topics_response
        schema:
          type: object
          properties:
              topic_list:
                  type: array
                  items:
                    type: object
                    properties:
                        topic:
                            type: string
                        summary:
                            type: string
                    required:
                        - topic
                        - summary
                    additionalProperties: false
          required:
              - topic_list
          additionalProperties: false
        strict: true

