name: OpenAI Single  # Name of the summarization.
summary_type: single document # Summarization type.
provider: openai # Provider of the summarization.
description: Performs single document summarization. # Description of the summarization.
version: 1.0.0 # Version of the summarization workflow.
recommended_num_texts: 1 # Recommended number of texts for summarization.
summarizer: # Summarizer configuration.
  cls: OpenAISingleDocSummarizer  # name of class that is subclass of Summarizer
  config: # configuration for defined class
    api:  # OpenAI API configuration.
      api_key:  # OpenAI API key.
      base_url: # Base URL for API.
    model: gpt-4o-mini # Name of model that should be used.
    prompt_builder: # Prompt builder. Available fields are: text.
      template: |  # Jinja2 template for prompt sequence. It can be a string, dictionary with keys 'segment_name' and 'template', or a sequence of messages with role and content. If you use dictionary all parts will be concatenated and SegmentedString will be used for the rendered result.
        Vytvoř krátký souhrn následujícího textu. Souhrn by měl být výstižný a obsahovat klíčové informace z textu. Neměl by být delší než 3 věty.
        Použij současnou češtinu, přestože výsledky vyhledávání ji používat nemusí.
        
        {{text}}
      role_key_form: role # How the dict key would be named in built prompt sequence. Doesn't affect key name in template config.
      content_key_form: content # How the dict key would be named in built prompt sequence. Doesn't affect key name in template config.
    structured_2_str: '{{label}}: {{content}}' # Jinja template for converting item of structured summary to string (available fields: label, content).
