services:
  summarization-api:
    restart: always
    build:
      context: .
      target: backend
      dockerfile: Dockerfile
      args:
        - now=$now
    #ports:
	#8005:8000
    env_file:
      - .env
